#!/usr/bin/env node

console.log('🔍 FHE GM Contract Manual Verification');
console.log('=====================================');
console.log('');
console.log('📋 Contract Information:');
console.log('   Address: 0x72eEA702E909599bC92f75774c5f1cE41b8B59BA');
console.log('   Network: Sepolia Testnet');
console.log('   Name: FHEGMContract');
console.log('');
console.log('🔗 Verification Links:');
console.log('   Etherscan: https://sepolia.etherscan.io/address/0x72eEA702E909599bC92f75774c5f1cE41b8B59BA');
console.log('   Verify Page: https://sepolia.etherscan.io/verifyContract');
console.log('');
console.log('📝 Manual Verification Steps:');
console.log('1. Go to: https://sepolia.etherscan.io/address/0x72eEA702E909599bC92f75774c5f1cE41b8B59BA');
console.log('2. Click "Contract" tab');
console.log('3. Click "Verify and Publish"');
console.log('4. Fill in the details:');
console.log('   - Contract Address: 0x72eEA702E909599bC92f75774c5f1cE41b8B59BA');
console.log('   - Contract Name: FHEGMContract');
console.log('   - Compiler Version: 0.8.19 (or try: v0.8.19, 0.8.20, 0.8.21)');
console.log('   - Optimization: Yes (200 runs)');
console.log('   - EVM Version: paris');
console.log('   - License: MIT License (MIT)');
console.log('5. Copy the source code from CONTRACT_VERIFICATION.md');
console.log('6. Submit verification');
console.log('');
console.log('⚠️  Important Notes:');
console.log('   - Try different compiler versions if one fails:');
console.log('     * 0.8.19');
console.log('     * v0.8.19');
console.log('     * 0.8.20');
console.log('     * 0.8.21');
console.log('   - Ensure optimization settings match');
console.log('   - Copy the source code exactly as provided');
console.log('   - Leave constructor arguments empty');
console.log('');
console.log('✅ After verification:');
console.log('   - Contract source code will be visible on Etherscan');
console.log('   - Users can interact with the contract through Etherscan');
console.log('   - The contract will be publicly verified');
console.log('');
console.log('🎯 Quick Links:');
console.log('   - Contract: https://sepolia.etherscan.io/address/0x72eEA702E909599bC92f75774c5f1cE41b8B59BA');
console.log('   - Etherscan API: https://etherscan.io/apis');
console.log('   - Verification Guide: CONTRACT_VERIFICATION.md');
console.log('');
console.log('🚀 Ready to verify! Follow the manual steps above.'); 